# Generated by Django 4.2.11 on 2024-03-21 16:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "nice_feeling",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятного чувства"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=7, verbose_name="Частота выполнения привычки"
                    ),
                ),
                (
                    "last_completed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последний срок"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="Feeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=255, verbose_name="Место действия"),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "nice_feeling",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятного чувства"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "once a week"), (2, "every day")],
                        default=2,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.timedelta(seconds=500)
                            )
                        ],
                        verbose_name="Время завершения",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чувство",
                "verbose_name_plural": "Чувства",
            },
        ),
    ]
