# Generated by Django 4.2.11 on 2024-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_habit_duration_habit_place_habit_related_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(verbose_name="Время выполнения привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=255, verbose_name="Место действия"),
        ),
    ]
