# Generated by Django 4.2.11 on 2024-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0003_alter_habit_duration_alter_habit_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[("day", "раз в день"), ("week", "раз в неделю")],
                default="day",
                max_length=50,
                verbose_name="периодичность",
            ),
        ),
    ]
